'use client'
import { useState } from 'react'

export default function Careers() {
  const [submitted, setSubmitted] = useState(false)
    const [form, setForm] = useState({ name: '', phone: '', email: '', position: '', location: '', comments: '' })

      const handleChange = (e) => setForm({ ...form, [e.target.name]: e.target.value })

        const handleSubmit = (e) => {
            e.preventDefault()
                const mailto = `mailto:info@still88.com?subject=Job Application - ${form.position}&body=Name: ${form.name}%0APhone: ${form.phone}%0AEmail: ${form.email}%0APosition: ${form.position}%0ALocation: ${form.location}%0AComments: ${form.comments}`
                    window.location.href = mailto
                        setSubmitted(true)
                          }

                            return (
                                <>
                                      <section className="bg-[#0a1628] py-32 px-6 text-center">
                                              <p className="text-[#c9a96e] text-sm tracking-widest uppercase mb-4">Join Our Team</p>
                                                      <h1 className="text-white text-4xl md:text-5xl font-playfair font-light">Careers</h1>
                                                            </section>

                                                                  <section className="py-24 px-6 bg-white">
                                                                          <div className="max-w-3xl mx-auto">
                                                                                    <div className="text-center mb-16">
                                                                                                <p className="text-gray-600 text-lg leading-relaxed">
                                                                                                              At still88, we believe our team is our greatest asset. We are always looking for talented individuals who share our commitment to excellence in hospitality.
                                                                                                                          </p>
                                                                                                                                    </div>
                                                                                                                                    
                                                                                                                                              {submitted ? (
                                                                                                                                                          <div className="text-center py-16 border border-[#c9a96e]">
                                                                                                                                                                        <p className="text-[#c9a96e] text-sm tracking-widest uppercase mb-4">Thank You</p>
                                                                                                                                                                                      <h2 className="text-2xl font-playfair text-[#0a1628]">Application Submitted</h2>
                                                                                                                                                                                                    <p className="text-gray-500 mt-4">We will be in touch shortly.</p>
                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                          ) : (
                                                                                                                                                                                                                                      <form onSubmit={handleSubmit} className="space-y-6">
                                                                                                                                                                                                                                                    <div className="grid md:grid-cols-2 gap-6">
                                                                                                                                                                                                                                                                    <div>
                                                                                                                                                                                                                                                                                      <label className="block text-xs tracking-widest uppercase text-gray-500 mb-2">Name *</label>
                                                                                                                                                                                                                                                                                                        <input name="name" required value={form.name} onChange={handleChange}
                                                                                                                                                                                                                                                                                                                            className="w-full border border-gray-200 px-4 py-3 text-sm focus:outline-none focus:border-[#c9a96e] transition-colors" />
                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                            <div>
                                                                                                                                                                                                                                                                                                                                                                              <label className="block text-xs tracking-widest uppercase text-gray-500 mb-2">Phone *</label>
                                                                                                                                                                                                                                                                                                                                                                                                <input name="phone" required value={form.phone} onChange={handleChange}
                                                                                                                                                                                                                                                                                                                                                                                                                    className="w-full border border-gray-200 px-4 py-3 text-sm focus:outline-none focus:border-[#c9a96e] transition-colors" />
                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <label className="block text-xs tracking-widest uppercase text-gray-500 mb-2">Email *</label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <input name="email" type="email" required value={form.email} onChange={handleChange}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  className="w-full border border-gray-200 px-4 py-3 text-sm focus:outline-none focus:border-[#c9a96e] transition-colors" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="grid md:grid-cols-2 gap-6">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <label className="block text-xs tracking-widest uppercase text-gray-500 mb-2">Position Applying For *</label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <input name="position" required value={form.position} onChange={handleChange}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      className="w-full border border-gray-200 px-4 py-3 text-sm focus:outline-none focus:border-[#c9a96e] transition-colors" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <label className="block text-xs tracking-widest uppercase text-gray-500 mb-2">Location *</label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <input name="location" required value={form.location} onChange={handleChange}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              className="w-full border border-gray-200 px-4 py-3 text-sm focus:outline-none focus:border-[#c9a96e] transition-colors" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <label className="block text-xs tracking-widest uppercase text-gray-500 mb-2">Comments</label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <textarea name="comments" rows={4} value={form.comments} onChange={handleChange}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            className="w-full border border-gray-200 px-4 py-3 text-sm focus:outline-none focus:border-[#c9a96e] transition-colors resize-none" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="pt-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <button type="submit" className="w-full bg-[#0a1628] text-white py-4 text-sm tracking-widest uppercase hover:bg-[#c9a96e] hover:text-[#0a1628] transition-colors duration-300 font-medium">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Submit Application
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <p className="text-gray-400 text-xs text-center">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Or email your resume directly to{' '}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <a href="mailto:info@still88.com" className="text-[#c9a96e] hover:underline">info@still88.com</a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </form>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </section>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
