import Link from 'next/link'

export default function Home() {
  return (
      <>
            {/* Hero */}
                  <section className="relative min-h-screen flex items-center justify-center bg-[#0a1628] overflow-hidden">
                          <div className="absolute inset-0 bg-gradient-to-br from-[#0a1628] via-[#112240] to-[#0a1628] opacity-95" />
                                  <div className="absolute inset-0 opacity-10" style={{backgroundImage: "url('/hero.jpg')", backgroundSize: 'cover', backgroundPosition: 'center'}} />
                                          <div className="relative z-10 text-center px-6 max-w-4xl mx-auto">
                                                    <div className="mb-8">
                                                                <span className="text-[#c9a96e] text-6xl font-playfair font-bold tracking-widest">88</span>
                                                                          </div>
                                                                                    <h1 className="text-white text-4xl md:text-5xl lg:text-6xl font-playfair font-light leading-tight mb-8">
                                                                                                Focused vision, strong values, a long-term strategy and a history of excellence.
                                                                                                          </h1>
                                                                                                                    <p className="text-gray-300 text-lg md:text-xl leading-relaxed mb-10 max-w-3xl mx-auto">
                                                                                                                                At still88, our foundation is built on unwavering commitments—to our dedicated team members, the communities we serve and our investors. Our investment philosophy is straightforward: we focus on creating sustainable, measured value.
                                                                                                                                          </p>
                                                                                                                                                    <Link href="/services" className="inline-block bg-[#c9a96e] text-[#0a1628] px-10 py-4 text-sm font-semibold tracking-widest uppercase hover:bg-white transition-colors duration-300">
                                                                                                                                                                Our Services
                                                                                                                                                                          </Link>
                                                                                                                                                                                  </div>
                                                                                                                                                                                        </section>
                                                                                                                                                                                        
                                                                                                                                                                                              {/* About */}
                                                                                                                                                                                                    <section className="py-24 px-6 bg-white">
                                                                                                                                                                                                            <div className="max-w-5xl mx-auto text-center">
                                                                                                                                                                                                                      <p className="text-[#c9a96e] text-sm tracking-widest uppercase mb-4">About still88</p>
                                                                                                                                                                                                                                <h2 className="text-3xl md:text-4xl font-playfair text-[#0a1628] mb-8 leading-tight">
                                                                                                                                                                                                                                            A proven track record in commercial investment
                                                                                                                                                                                                                                                      </h2>
                                                                                                                                                                                                                                                                <p className="text-gray-600 text-lg leading-relaxed max-w-3xl mx-auto mb-6">
                                                                                                                                                                                                                                                                            By employing established methodologies and innovative strategies, still88 has developed a proven track record in identifying and seizing commercial investment opportunities that yield exceptional returns. We are dedicated to not just meeting expectations, but exceeding them, fostering growth and success for all involved.
                                                                                                                                                                                                                                                                                      </p>
                                                                                                                                                                                                                                                                                                <Link href="/services" className="text-[#c9a96e] text-sm tracking-widest uppercase font-semibold hover:text-[#0a1628] transition-colors border-b border-[#c9a96e] pb-1">
                                                                                                                                                                                                                                                                                                            Read More
                                                                                                                                                                                                                                                                                                                      </Link>
                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                    </section>
                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                          {/* Services Preview */}
                                                                                                                                                                                                                                                                                                                                                <section className="py-24 px-6 bg-gray-50">
                                                                                                                                                                                                                                                                                                                                                        <div className="max-w-6xl mx-auto">
                                                                                                                                                                                                                                                                                                                                                                  <div className="text-center mb-16">
                                                                                                                                                                                                                                                                                                                                                                              <p className="text-[#c9a96e] text-sm tracking-widest uppercase mb-4">What We Do</p>
                                                                                                                                                                                                                                                                                                                                                                                          <h2 className="text-3xl md:text-4xl font-playfair text-[#0a1628]">Our Services</h2>
                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                              <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8">
                                                                                                                                                                                                                                                                                                                                                                                                                          {[
                                                                                                                                                                                                                                                                                                                                                                                                                                        { title: 'Development', desc: 'Transforming visionary concepts into stunning hotel properties that drive profitability.' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                      { title: 'Operations', desc: 'Hands-on operational management ensuring exceptional guest experiences and strong returns.' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    { title: 'Strategic Consulting', desc: 'Expert guidance and strategic foresight to navigate market dynamics.' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  { title: 'Advisory Services', desc: 'Expert testimony, asset valuations, and litigation support for hospitality assets.' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ].map((s) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div key={s.title} className="bg-white p-8 border border-gray-100 hover:border-[#c9a96e] transition-colors duration-300 group">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="w-8 h-0.5 bg-[#c9a96e] mb-6 group-hover:w-16 transition-all duration-300" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <h3 className="text-xl font-playfair text-[#0a1628] mb-4">{s.title}</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <p className="text-gray-500 text-sm leading-relaxed">{s.desc}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="text-center mt-12">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <Link href="/services" className="inline-block border border-[#0a1628] text-[#0a1628] px-10 py-4 text-sm font-semibold tracking-widest uppercase hover:bg-[#0a1628] hover:text-white transition-colors duration-300">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    View All Services
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </Link>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </section>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {/* Partners */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <section className="py-24 px-6 bg-white">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="max-w-5xl mx-auto text-center">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <p className="text-[#c9a96e] text-sm tracking-widest uppercase mb-4">Our Partners</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <h2 className="text-3xl font-playfair text-[#0a1628] mb-16">Trusted by Industry Leaders</h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="flex flex-wrap justify-center items-center gap-16">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {['Marriott International', 'Hilton', 'Kriya Hotels'].map((p) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div key={p} className="text-gray-400 text-lg font-semibold tracking-wider uppercase">{p}</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </section>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
